name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Or specify the branch you want to trigger deployment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'  # Use Node.js version 18 or higher

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build -- --configuration production

    - name: Install Firebase CLI
      run: npm install -g firebase-tools  # Install Firebase CLI

    - name: Deploy to Firebase Hosting
      run: firebase deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}  # Use the token stored in GitHub secrets
