name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build -- --configuration production

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Check if Firebase token is set
      run: |
        if [ -z "$FIREBASE_TOKEN" ]; then
          echo "Firebase token is not set."
          exit 1
        else
          echo "Firebase token is set correctly."
        fi
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

    - name: Deploy to Firebase Hosting
      run: firebase deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
